<a href="https://colab.research.google.com/github/harpreet-kaur-mahant/LearningPython/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [21]:
#single dimensional numpy array
n1 = np.array([1,2,3,4,5])
n1

array([1, 2, 3, 4, 5])

In [6]:
type(n1)

numpy.ndarray

In [0]:
#multi dimensional numpy array
n2 = np.array([ [6,7,8,9,10], [11,12,13,14,15] ])

In [9]:
n2

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [10]:
type(n2)

numpy.ndarray

In [14]:
#intialize numpy array with all zeros
n3 = np.zeros( (1,2))
n3

array([[0., 0.]])

In [16]:
n4 = np.zeros( (4,5))
n4

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
#itialaziing numpy array with full values
n5 = np.full( (2,3), 10)
n5

array([[10, 10, 10],
       [10, 10, 10]])

In [22]:
#initialize numpy array within a range
n6 = np.arange(10,20)
n6

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [27]:
n7 = np.arange(10,21)
n7

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [28]:
n8 = np.arange( 10, 50 , 5)
n8

array([10, 15, 20, 25, 30, 35, 40, 45])

In [29]:
n9 = np.arange( 10, 51 , 5)
n9

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

In [31]:
# initalize numpy array with random numbers
n10 = np.random.randint(1, 100, 5)
n10

array([95, 19,  9, 28, 18])

In [0]:
# Changing shape of an array

In [39]:
n11 = np.array( [ [1,2,3,4] , [5,6,7,8] ] )
n11

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [40]:
n11.shape

(2, 4)

In [0]:
n11.shape = (4,2)

In [42]:
n11

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [0]:
#ADDITION OF NUMPY ARRAYS

In [0]:
array1 = np.array( [ 10, 20 ])
array2 = np.array( [ 30, 40 ])

In [48]:
# Addition of numpy array without axis means addition of all values in the array
np.sum( [array1 , array2])

100

In [50]:
# Addition of numpy array with  axis = 0 means addition of all values in the array vertically
np.sum( [array1 , array2] , axis = 0 )

array([40, 60])

In [51]:
# Addition of numpy array with  axis = 1 means addition of all values in the array horizontally
np.sum( [array1 , array2] , axis = 1 )

array([30, 70])

In [0]:
#JOINING OF NUMPY ARRAYS

In [0]:
n1 = np.array( [10,20,30] )
n2 = np.array( [40,50,60] )

In [56]:
# v-stack = vertical stack = stack arrays row-wise
np.vstack( [ n1, n2 ])

array([[10, 20, 30],
       [40, 50, 60]])

In [58]:
# h-stack = horizontal stack = stack arrays column-wise
np.hstack( [ n1, n2 ])

array([10, 20, 30, 40, 50, 60])

In [59]:
# column_stack = horizontal stack = stack arrays column-wise
np.column_stack( [ n1, n2 ])

array([[10, 40],
       [20, 50],
       [30, 60]])